import { getCorsHeaders, handleCorsPreflightRequest } from "../_shared/cors.ts";
import { requireAuth, getServiceClient } from "../_shared/auth.ts";

Deno.serve(async (req) => {
  const preflight = handleCorsPreflightRequest(req);
  if (preflight) return preflight;

  const corsHeaders = getCorsHeaders(req);

  try {
    const { userId, supabase } = await requireAuth(req);
    const { trip_id, invited_email, role = "collaborator" } = await req.json();

    if (!trip_id || !invited_email) {
      return new Response(JSON.stringify({ error: "trip_id and invited_email are required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (!["collaborator", "viewer"].includes(role)) {
      return new Response(JSON.stringify({ error: "role must be collaborator or viewer" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Verify the calling user owns this trip
    const { data: trip } = await supabase
      .from("trips")
      .select("id, destination, user_id")
      .eq("id", trip_id)
      .single();

    if (!trip || trip.user_id !== userId) {
      return new Response(JSON.stringify({ error: "Only the trip owner can send invites" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Check for duplicate invite
    const { data: existing } = await supabase
      .from("trip_collaborators")
      .select("id, status")
      .eq("trip_id", trip_id)
      .eq("invited_email", invited_email.toLowerCase().trim())
      .maybeSingle();

    if (existing) {
      const msg = existing.status === "accepted"
        ? "This person has already joined the trip"
        : "An invite has already been sent to this email";
      return new Response(JSON.stringify({ error: msg }), {
        status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get inviter's profile
    const { data: inviterProfile } = await supabase
      .from("profiles")
      .select("name, handle, avatar_url")
      .eq("user_id", userId)
      .single();

    // Create invite row (invite_token auto-generated by DB default)
    const { data: invite, error: inviteError } = await supabase
      .from("trip_collaborators")
      .insert({
        trip_id,
        invited_email: invited_email.toLowerCase().trim(),
        role,
        status: "pending",
        invited_by: userId,
      })
      .select("invite_token")
      .single();

    if (inviteError) throw inviteError;

    // Notify the invited user if they already have an account
    try {
      const svc = getServiceClient();
      const { data: { users } } = await svc.auth.admin.listUsers({ page: 1, perPage: 1000 });
      const invitedAuthUser = users?.find((u: any) => u.email?.toLowerCase() === invited_email.toLowerCase().trim());
      if (invitedAuthUser) {
        const { createNotification } = await import("../create-notification/index.ts");
        await createNotification({
          user_id: invitedAuthUser.id,
          trip_id,
          type: "invite_received",
          title: `${inviterProfile?.name || "Someone"} invited you to join their trip to ${trip.destination}`,
          action_url: `/invite/${invite.invite_token}`,
        });
      }
    } catch (notifErr) {
      console.error("invite notification error:", notifErr instanceof Error ? notifErr.message : String(notifErr));
    }

    const siteUrl = Deno.env.get("SITE_URL") || "https://conciergestyled.com";

    return new Response(
      JSON.stringify({
        invite_token: invite.invite_token,
        invite_url: `${siteUrl}/invite/${invite.invite_token}`,
        inviter_name: inviterProfile?.name,
        inviter_handle: inviterProfile?.handle,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: err.name === "AuthError" ? 401 : 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
