import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import Navbar from "@/components/layout/Navbar";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section className="mb-10">
    <h2 className="text-xl font-heading mb-4">{title}</h2>
    <div className="text-sm text-muted-foreground font-body leading-relaxed space-y-3">{children}</div>
  </section>
);

const Terms = () => (
  <div className="min-h-screen bg-background">
    <Navbar />
    <main className="pt-28 pb-24 px-6">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-2xl mx-auto"
      >
        <p className="text-[11px] tracking-[0.3em] uppercase text-primary mb-3 font-body">Legal</p>
        <h1 className="text-4xl font-heading mb-3">Terms of Service</h1>
        <p className="text-xs text-muted-foreground font-body mb-12">Last updated: March 2026</p>

        <Section title="1. Service Description">
          <p>
            Concierge Styled (&quot;we&quot;, &quot;our&quot;, &quot;the Service&quot;) is an AI-powered travel styling
            platform that provides outfit suggestions, packing recommendations, activity ideas, and trip
            planning tools for personal travel. By creating an account or using the Service, you agree
            to these Terms.
          </p>
        </Section>

        <Section title="2. Eligibility & Account">
          <p>
            You must be at least 16 years old to use the Service. You are responsible for maintaining
            the security of your account credentials and for all activity under your account.
          </p>
          <p>
            You agree not to share your account, attempt to reverse-engineer the Service, use it for
            commercial resale, or violate any applicable law.
          </p>
        </Section>

        <Section title="3. Subscription Plans">
          <p>
            We offer three membership tiers: Free, Luxe, and Atelier. Features available on each tier
            are described on the <Link to="/pricing" className="text-primary hover:underline">Pricing page</Link>.
          </p>
          <p>
            <strong className="text-foreground">Monthly subscriptions</strong> are billed every 30 days.
            You may cancel at any time from your Settings page. Access continues until the end of the
            current billing period — no partial refunds are issued.
          </p>
          <p>
            <strong className="text-foreground">Annual subscriptions</strong> are billed upfront for
            12 months. A full refund is available within 14 days of purchase. After 14 days, the
            subscription is non-refundable but access continues for the remainder of the year.
          </p>
          <p>
            We reserve the right to change pricing with 30 days' notice to existing subscribers.
          </p>
        </Section>

        <Section title="4. AI-Generated Content">
          <p>
            Outfit suggestions, packing lists, briefings, and other AI outputs are generated by
            large language models and should be treated as suggestions, not professional advice.
            We make no guarantee of accuracy. Always verify health, visa, and safety information
            with official sources before travelling.
          </p>
          <p>
            You own the content you create (trip data, board images, notes). You grant us a limited
            licence to store and process it to deliver the Service.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service to generate harmful, illegal, or misleading content</li>
            <li>Attempt to circumvent subscription tier limits by technical means</li>
            <li>Scrape, copy, or redistribute Service output for commercial purposes</li>
            <li>Upload content that infringes third-party intellectual property</li>
          </ul>
        </Section>

        <Section title="6. Intellectual Property">
          <p>
            The Concierge Styled name, logo, product design, and underlying technology are our
            intellectual property. Nothing in these Terms transfers ownership to you.
          </p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent
            permitted by law, we are not liable for any indirect, incidental, or consequential
            damages arising from your use of the Service, including but not limited to travel
            decisions made based on AI-generated recommendations.
          </p>
          <p>
            Our total liability to you for any claim shall not exceed the amount you paid to us
            in the 12 months preceding the claim.
          </p>
        </Section>

        <Section title="8. Termination">
          <p>
            We may suspend or terminate your account if you breach these Terms, with or without
            notice. You may delete your account at any time from your Settings page — this will
            cancel any active subscription and permanently delete your data.
          </p>
        </Section>

        <Section title="9. Governing Law">
          <p>
            These Terms are governed by the laws of England and Wales. Any disputes shall be
            subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </Section>

        <Section title="10. Contact">
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:hello@conciergestyle.com" className="text-primary hover:underline">
              hello@conciergestyle.com
            </a>
            .
          </p>
        </Section>
      </motion.div>
    </main>

    <footer className="border-t border-border py-10 px-6 text-center">
      <p className="text-xs text-muted-foreground font-body">
        © 2026 Concierge Styled.{" "}
        <Link to="/terms" className="hover:text-foreground transition-colors">Terms</Link>
        {" · "}
        <Link to="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
      </p>
    </footer>
  </div>
);

export default Terms;
