
-- Outfit suggestions generated by AI
CREATE TABLE public.outfit_suggestions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  occasion TEXT,
  description TEXT,
  items JSONB NOT NULL DEFAULT '[]',
  pinned BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.outfit_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own outfit suggestions"
ON public.outfit_suggestions FOR SELECT USING (is_trip_owner(trip_id));

CREATE POLICY "Users can insert outfit suggestions"
ON public.outfit_suggestions FOR INSERT WITH CHECK (is_trip_owner(trip_id));

CREATE POLICY "Users can update own outfit suggestions"
ON public.outfit_suggestions FOR UPDATE USING (is_trip_owner(trip_id));

CREATE POLICY "Users can delete own outfit suggestions"
ON public.outfit_suggestions FOR DELETE USING (is_trip_owner(trip_id));

CREATE INDEX idx_outfit_suggestions_trip ON public.outfit_suggestions(trip_id);

-- Activity suggestions
CREATE TABLE public.activity_suggestions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  location TEXT,
  rating REAL,
  price_level TEXT,
  image_url TEXT,
  source_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.activity_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own activity suggestions"
ON public.activity_suggestions FOR SELECT USING (is_trip_owner(trip_id));

CREATE POLICY "Users can insert activity suggestions"
ON public.activity_suggestions FOR INSERT WITH CHECK (is_trip_owner(trip_id));

CREATE POLICY "Users can update own activity suggestions"
ON public.activity_suggestions FOR UPDATE USING (is_trip_owner(trip_id));

CREATE POLICY "Users can delete own activity suggestions"
ON public.activity_suggestions FOR DELETE USING (is_trip_owner(trip_id));

CREATE INDEX idx_activity_suggestions_trip ON public.activity_suggestions(trip_id);
